# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
EMBED_API: 'AIzaSyCot-cF6mA-9mkOiOBaFsEwKRcTPJxrZqI'
MAPS: 'AIzaSyCaOPw-q9E9srNzO8IEiAxiKPLIVnrX0nQ'
Twilio_sid: AC0326b107b2f72cb03da6fca712c3c5b5
twil_token: 2b77c01d1b2fbd4040cccf903abc4c5c
stripe_pub: pk_test_L8EUExcGHGFUfidRubx0ef40
stripe_secret: sk_test_kcSV0wtWZ40eSnmIlbRQEr2O
stripe_connect: ca_CS416F1yHiYHmW9PqmCGo1Gue3Fg6lD9
